### ISSUE TITLE
Make this application work with repos in the nearform-actions organization

### ISSUE THREAD

**Issue by simoneb** [nearform/unbreakci#261]
Now that we're moving repos to the nearform-actions org, we should make this work against that organization as well. We need to figure out what needs to be done for that to happen, and make changes accordingly.

**Comment by MelkorNemesis** [comment]
To further clarify this, we want the app to be able to pick up failed pull request checks from `nearform-actions` organization and attach them to `nearform` technology hub board.

We discussed this with @simoneb and there are some limitations to be considered:

1. We can't install this app on `nearform-actions` organisation because we would have to make the app public.
2. We certainly don't want two instances of the same app running in a GCP.
3. Currently the app only knows how to get information about a pull request from the `nearform` organization, because that's where the app is installed. We need to query the pull request details to see if the author of the pull request was `dependabot`.

One idea that we had was to create a separate app installed in the `nearform-actions` that would listen for the `pull_request` and `check_suite` events and send those over to the app installed in a `nearform` organization and somehow do the processing in that app.

Also it's not very easy to get this app running locally which makes the testing bit difficult.
